# Generated by Django 4.2.16 on 2024-10-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id_mbti_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
